export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'
export const INCREAMENT_TO_QUANTITY = 'INCREAMENT_TO_QUANTITY'
export const DECREAMENT_ITEM_QUANTITY = 'DECREAMENT_ITEM_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'

